### ISSUE TITLE
ウォーミングアップ

### ISSUE THREAD

**Issue by yamoyamoto** [yamoyamoto/firebase_sample#1]
## TODO

- [x] [Cloud Function (Web API)](https://firebase.google.com/docs/functions?hl=ja)
- [x] [FireStore](https://firebase.google.com/docs/firestore?hl=ja)
- [ ] [Authentication](https://firebase.google.com/docs/auth?hl=ja)
- [x] Jest
- [x] GitHub Actions
